version: '3.9'
services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ezequiel
      POSTGRES_PASSWORD: chichito
    ports:
      - 5432:5432
  nest:
    build:
      context: ./nest
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgresql
  dotnet:
    build:
      context: ./netcoretest
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgresql
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=regaldo.ezequiel@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=chichito
    depends_on:
      - postgresql
