version: '3.9'
services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ezequiel
      POSTGRES_PASSWORD: chichito
    ports:
      - 5432:5432
  nest:
    build:
      context: ./nest
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  dotnet:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    ports:
      - 5000:5000
