version: '3.9'
services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ezequiel
      POSTGRES_PASSWORD: chichito
      POSTGRES_MAX_CONNECTIONS: 12000
    ports:
      - 5432:5432
  springreactive:
    build:
      context: ./demo-reactive
      dockerfile: Dockerfile
    ports:
      - 3400:3400
    depends_on:
      - postgresql
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=regaldo.ezequiel@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=chichito
    depends_on:
      - postgresql
